feat: Memory macro
lurk-lab/loam pull request #10
Opened 2024-11-15 01:15 UTC by winston-h-zhang

This PR implements a `defmem` macro to automatically generate memory program. We have 3 types of memory:
- `full`: These are fully specified memories like `cons`, `fun`.
- `digest-only`: These are memories that only support digests, like `builtin`.
- `immediate`: These are for immediate types like `num`.

Depends on #9, please merge that first.

2024-11-15 01:26 UTC, porcuquine commented on loam/allocation.lisp
> +  (relation (unhash4 element wide)) ; (tag digest)
Why make this change?

2025-01-15 21:42 UTC, porcuquine commented on loam/allocation.lisp
> +(defmacro defmem (prog-name superclasses config &body arg-specs)
Whatever we decide, let's have it live in only one place rather than duplicate and comment.

2025-01-16 01:28 UTC, porcuquine commented on loam/evaluation.lisp
> +    (intern (format nil "~A~A" root suf)))
You can use [symbolconc](https://github.com/lurk-lab/loam/blob/main/base/macros.lisp#L19-L20)

2025-01-16 01:37 UTC, porcuquine commented on loam/evaluation.lisp
> +;;
I'm not totally following the issue, but it's not worth getting into the weeds on now, so let's just live with this comment.

2025-01-16 01:39 UTC, porcuquine requested changes
This looks pretty good. I didn't thoroughly check the actual macro, but it seems reasonable and tests are passing. Please just add a test of the macroexpansion for the most complicated case (which I think is cons-mem?) — so we have a clear record of the intended behavior.

2025-01-17 01:07 UTC, winston-h-zhang commented
The most complicated case is `fun-mem`, I already had spec tests for that and the two other cases (it's the very first test, but kind of in the weeds so you might've missed it):
```lisp
(test mem-spec
  (is (compare-spec 'fun-mem 'syn-fun-mem))
  (is (compare-spec 'sym-digest-mem 'syn-sym-digest-mem))
  (is (compare-spec 'immediate-num 'syn-immediate-num)))
```

2025-01-17 01:08 UTC, winston-h-zhang commented on loam/allocation.lisp
> +(defmacro defmem (prog-name superclasses config &body arg-specs)
I've deleted

2025-01-17 01:09 UTC, winston-h-zhang commented on loam/allocation.lisp
> +  (relation (unhash4 element wide)) ; (tag digest)
Leaving this comment for context coming back in the future. Originally, I removed the tag because to combine all the hashing logic between the different memories, e.g. getting a hash4 from `Cons` v.s. `Thunk` goes through the same hashing pipeline.

However, when writing out the macro, it's easier to keep each completely separate. I added back in the tag to differentiate and deduplicate the hashing.

2025-01-17 01:33 UTC, porcuquine commented on loam/evaluation.lisp
> +        `(progn
Formatting looks wonky here.

2025-01-17 01:40 UTC, porcuquine commented
Please don't force-push over commits implementing review.

2025-01-20 20:33 UTC, porcuquine commented
> The most complicated case is `fun-mem`, I already had spec tests for that and the two other cases (it's the very first test, but kind of in the weeds so you might've missed it):
> 
> ```commonlisp
> (test mem-spec
>   (is (compare-spec 'fun-mem 'syn-fun-mem))
>   (is (compare-spec 'sym-digest-mem 'syn-sym-digest-mem))
>   (is (compare-spec 'immediate-num 'syn-immediate-num)))
> ```

Got it, looks good then.

2025-01-20 20:33 UTC, porcuquine approved these changes

2025-01-21 17:33 UTC, merged